language: android
jdk:
- oraclejdk7
- openjdk6
env:
  matrix:
      - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
android:
  components:
      - build-tools-21.1.2
script:
- cd app/android/Sensorama
- ./gradlew assembleDebug
